import type { Locale } from "./types";

const copy: Record<Locale, Record<string, string>> = {
  en: {
    "Foundation Level": "Foundation Level",
    "XP to next level": "XP to next level",
    "Profile Identity": "Profile Identity",
    "Equipped rewards": "Equipped rewards",
    "Inventory": "Inventory",
    "Equip": "Equip",
    "Equipped": "Equipped",
    "Unequip": "Unequip",
    "No items yet": "No items yet",
    "Complete missions and achievements to earn profile items.": "Complete missions and achievements to earn profile items.",
    "Rewards & Shop": "Rewards & Shop",
    "Shop coming soon": "Shop coming soon",
    "Your currencies are ready, but spending is disabled during closed beta.": "Your currencies are ready, but spending is disabled during closed beta.",
    "Future rewards": "Future rewards",
    "Profile frames": "Profile frames",
    "Badges": "Badges",
    "Titles": "Titles",
    "Effects": "Effects",
    "Special challenges": "Special challenges",
    "Mission Complete": "Mission Complete",
    "Level up": "Level up",
    "New achievement": "New achievement",
    "New item": "New item",
    "Start here": "Start here",
    "Step 1": "Step 1",
    "Step 2": "Step 2",
    "Step 3": "Step 3",
    "Step 4": "Step 4",
    "Start the highlighted root mission.": "Start the highlighted root mission.",
    "Save evidence inside the mission panel.": "Save evidence inside the mission panel.",
    "Return later and complete it after the timer.": "Return later and complete it after the timer.",
    "This guide stays small. The Tree is for action.": "This guide stays small. The Tree is for action.",
    "Got it": "Got it",
    "Achievement Archive": "Achievement Archive",
    "Unlocked": "Unlocked",
    "Locked": "Locked",
    "Hidden reward": "Hidden reward",
    "Reward revealed after unlock.": "Reward revealed after unlock.",
    "Inventory Archive": "Inventory Archive",
    "Beta": "Beta",
    "Closed beta limitation": "Closed beta limitation",
    "Data deletion": "Data deletion",
    "Support": "Support"
  },
  ru: {
    "Foundation Level": "Уровень Основ",
    "XP to next level": "XP до следующего уровня",
    "Profile Identity": "Профиль игрока",
    "Equipped rewards": "Экипированные награды",
    "Inventory": "Инвентарь",
    "Equip": "Экипировать",
    "Equipped": "Экипировано",
    "Unequip": "Снять",
    "No items yet": "Предметов пока нет",
    "Complete missions and achievements to earn profile items.": "Выполняйте миссии и достижения, чтобы получать предметы профиля.",
    "Rewards & Shop": "Награды и магазин",
    "Shop coming soon": "Магазин скоро появится",
    "Your currencies are ready, but spending is disabled during closed beta.": "Валюты уже видны, но траты отключены на этапе закрытой беты.",
    "Future rewards": "Будущие награды",
    "Profile frames": "Рамки профиля",
    "Badges": "Значки",
    "Titles": "Титулы",
    "Effects": "Эффекты",
    "Special challenges": "Особые испытания",
    "Mission Complete": "Миссия завершена",
    "Level up": "Новый уровень",
    "New achievement": "Новое достижение",
    "New item": "Новый предмет",
    "Start here": "Начните здесь",
    "Step 1": "Шаг 1",
    "Step 2": "Шаг 2",
    "Step 3": "Шаг 3",
    "Step 4": "Шаг 4",
    "Start the highlighted root mission.": "Запустите подсвеченную корневую миссию.",
    "Save evidence inside the mission panel.": "Сохраните доказательство в панели миссии.",
    "Return later and complete it after the timer.": "Вернитесь позже и завершите после таймера.",
    "This guide stays small. The Tree is for action.": "Подсказка короткая. Дерево — для действия.",
    "Got it": "Понятно",
    "Achievement Archive": "Архив достижений",
    "Unlocked": "Открыто",
    "Locked": "Закрыто",
    "Hidden reward": "Скрытая награда",
    "Reward revealed after unlock.": "Награда откроется после выполнения.",
    "Inventory Archive": "Архив инвентаря",
    "Beta": "Бета",
    "Closed beta limitation": "Ограничение закрытой беты",
    "Data deletion": "Удаление данных",
    "Support": "Поддержка"
  },
  cs: {
    "Foundation Level": "Úroveň základů",
    "XP to next level": "XP do další úrovně",
    "Profile Identity": "Identita profilu",
    "Equipped rewards": "Vybavené odměny",
    "Inventory": "Inventář",
    "Equip": "Vybavit",
    "Equipped": "Vybaveno",
    "Unequip": "Sundat",
    "No items yet": "Zatím žádné předměty",
    "Complete missions and achievements to earn profile items.": "Plňte mise a úspěchy, abyste získali předměty profilu.",
    "Rewards & Shop": "Odměny a obchod",
    "Shop coming soon": "Obchod se připravuje",
    "Your currencies are ready, but spending is disabled during closed beta.": "Měny jsou připravené, ale utrácení je v uzavřené betě vypnuté.",
    "Future rewards": "Budoucí odměny",
    "Profile frames": "Rámečky profilu",
    "Badges": "Odznaky",
    "Titles": "Tituly",
    "Effects": "Efekty",
    "Special challenges": "Speciální výzvy",
    "Mission Complete": "Mise dokončena",
    "Level up": "Nová úroveň",
    "New achievement": "Nový úspěch",
    "New item": "Nový předmět",
    "Start here": "Začněte zde",
    "Step 1": "Krok 1",
    "Step 2": "Krok 2",
    "Step 3": "Krok 3",
    "Step 4": "Krok 4",
    "Start the highlighted root mission.": "Spusťte zvýrazněnou kořenovou misi.",
    "Save evidence inside the mission panel.": "Uložte důkaz v panelu mise.",
    "Return later and complete it after the timer.": "Vraťte se později a dokončete ji po časovači.",
    "This guide stays small. The Tree is for action.": "Nápověda zůstává krátká. Strom je pro akci.",
    "Got it": "Rozumím",
    "Achievement Archive": "Archiv úspěchů",
    "Unlocked": "Odemčeno",
    "Locked": "Zamčeno",
    "Hidden reward": "Skrytá odměna",
    "Reward revealed after unlock.": "Odměna se ukáže po odemčení.",
    "Inventory Archive": "Archiv inventáře",
    "Beta": "Beta",
    "Closed beta limitation": "Omezení uzavřené bety",
    "Data deletion": "Smazání dat",
    "Support": "Podpora"
  },
  uk: {
    "Foundation Level": "Рівень Основ",
    "XP to next level": "XP до наступного рівня",
    "Profile Identity": "Профіль гравця",
    "Equipped rewards": "Екіпіровані нагороди",
    "Inventory": "Інвентар",
    "Equip": "Екіпірувати",
    "Equipped": "Екіпіровано",
    "Unequip": "Зняти",
    "No items yet": "Предметів поки немає",
    "Complete missions and achievements to earn profile items.": "Виконуйте місії та досягнення, щоб отримувати предмети профілю.",
    "Rewards & Shop": "Нагороди й магазин",
    "Shop coming soon": "Магазин скоро з’явиться",
    "Your currencies are ready, but spending is disabled during closed beta.": "Валюти вже видно, але витрати вимкнені на етапі закритої бети.",
    "Future rewards": "Майбутні нагороди",
    "Profile frames": "Рамки профілю",
    "Badges": "Значки",
    "Titles": "Титули",
    "Effects": "Ефекти",
    "Special challenges": "Особливі випробування",
    "Mission Complete": "Місію завершено",
    "Level up": "Новий рівень",
    "New achievement": "Нове досягнення",
    "New item": "Новий предмет",
    "Start here": "Почніть тут",
    "Step 1": "Крок 1",
    "Step 2": "Крок 2",
    "Step 3": "Крок 3",
    "Step 4": "Крок 4",
    "Start the highlighted root mission.": "Запустіть підсвічену кореневу місію.",
    "Save evidence inside the mission panel.": "Збережіть доказ у панелі місії.",
    "Return later and complete it after the timer.": "Поверніться пізніше й завершіть після таймера.",
    "This guide stays small. The Tree is for action.": "Підказка коротка. Дерево — для дії.",
    "Got it": "Зрозуміло",
    "Achievement Archive": "Архів досягнень",
    "Unlocked": "Відкрито",
    "Locked": "Закрито",
    "Hidden reward": "Прихована нагорода",
    "Reward revealed after unlock.": "Нагорода відкриється після виконання.",
    "Inventory Archive": "Архів інвентаря",
    "Beta": "Бета",
    "Closed beta limitation": "Обмеження закритої бети",
    "Data deletion": "Видалення даних",
    "Support": "Підтримка"
  }
};

const itemCopy: Record<Locale, Record<string, { title: string; description: string }>> = {
  en: {},
  ru: {
    beta_tester_badge: { title: "Бета-тестер", description: "Вы присоединились к Habidoo во время создания Foundation shell." },
    beta_tester_frame: { title: "Сигнал основателя", description: "Сдержанная рамка профиля для ранних аккаунтов закрытой беты." },
    first_mission_badge: { title: "Первое доказательство", description: "Завершена первая реальная миссия Habidoo." },
    focus_seed_badge: { title: "Семя фокуса", description: "Создан первый объект фокуса для главы." },
    root_awakener_badge: { title: "Корень пробуждён", description: "Завершена первая корневая миссия ветки." },
    steady_three_badge: { title: "Три реальных шага", description: "Завершены три миссии с доказательствами." },
    foundation_pathfinder_frame: { title: "Проводник Основ", description: "Завершены четыре корня веток Эпохи основ." },
    awakening_title: { title: "Пробуждённый стратег", description: "Завершено Испытание пробуждения." }
  },
  cs: {
    beta_tester_badge: { title: "Beta tester", description: "Připojili jste se k Habidoo během tvorby Foundation shellu." },
    beta_tester_frame: { title: "Signál zakladatele", description: "Střídmý rámeček profilu pro rané účty uzavřené bety." },
    first_mission_badge: { title: "První důkaz", description: "Dokončena první skutečná mise Habidoo." },
    focus_seed_badge: { title: "Semínko soustředění", description: "Vytvořen první objekt soustředění pro kapitolu." },
    root_awakener_badge: { title: "Kořen probuzen", description: "Dokončena první kořenová mise větve." },
    steady_three_badge: { title: "Tři skutečné kroky", description: "Dokončeny tři mise s důkazy." },
    foundation_pathfinder_frame: { title: "Průzkumník základů", description: "Dokončeny čtyři kořeny větví Éry základů." },
    awakening_title: { title: "Probuzený stratég", description: "Dokončena Zkouška probuzení." }
  },
  uk: {
    beta_tester_badge: { title: "Бета-тестер", description: "Ви приєдналися до Habidoo під час створення Foundation shell." },
    beta_tester_frame: { title: "Сигнал засновника", description: "Стримана рамка профілю для ранніх акаунтів закритої бети." },
    first_mission_badge: { title: "Перший доказ", description: "Завершено першу реальну місію Habidoo." },
    focus_seed_badge: { title: "Насіння фокуса", description: "Створено перший об’єкт фокуса для глави." },
    root_awakener_badge: { title: "Корінь пробуджено", description: "Завершено першу кореневу місію гілки." },
    steady_three_badge: { title: "Три реальні кроки", description: "Завершено три місії з доказами." },
    foundation_pathfinder_frame: { title: "Провідник Основ", description: "Завершено чотири корені гілок Ери основ." },
    awakening_title: { title: "Пробуджений стратег", description: "Завершено Випробування пробудження." }
  }
};

const achievementCopy: Record<Locale, Record<string, { title: string; description: string }>> = {
  en: {},
  ru: {
    first_mission_completed: { title: "Первая миссия завершена", description: "Завершите любую реальную миссию." },
    first_focus_object_created: { title: "Первый объект фокуса", description: "Создайте первый объект фокуса." },
    first_branch_root_completed: { title: "Корень пробуждён", description: "Завершите корневую миссию любой ветки." },
    three_missions_completed: { title: "Три реальных шага", description: "Завершите три миссии с доказательствами." },
    four_branch_roots_completed: { title: "Проводник Основ", description: "Завершите четыре корня веток." },
    awakening_trial_completed: { title: "Испытание пробуждения", description: "Завершите испытание главы Foundation." },
    beta_tester_account: { title: "Основатель закрытой беты", description: "Создайте подтверждённый аккаунт Habidoo во время закрытой беты." }
  },
  cs: {
    first_mission_completed: { title: "První mise dokončena", description: "Dokončete jakoukoli skutečnou misi." },
    first_focus_object_created: { title: "První objekt soustředění", description: "Vytvořte první objekt soustředění." },
    first_branch_root_completed: { title: "Kořen probuzen", description: "Dokončete kořenovou misi libovolné větve." },
    three_missions_completed: { title: "Tři skutečné kroky", description: "Dokončete tři mise s důkazy." },
    four_branch_roots_completed: { title: "Průzkumník základů", description: "Dokončete čtyři kořeny větví." },
    awakening_trial_completed: { title: "Zkouška probuzení", description: "Dokončete zkoušku kapitoly Foundation." },
    beta_tester_account: { title: "Zakladatel uzavřené bety", description: "Vytvořte potvrzený účet Habidoo během uzavřené bety." }
  },
  uk: {
    first_mission_completed: { title: "Першу місію завершено", description: "Завершіть будь-яку реальну місію." },
    first_focus_object_created: { title: "Перший об’єкт фокуса", description: "Створіть перший об’єкт фокуса." },
    first_branch_root_completed: { title: "Корінь пробуджено", description: "Завершіть кореневу місію будь-якої гілки." },
    three_missions_completed: { title: "Три реальні кроки", description: "Завершіть три місії з доказами." },
    four_branch_roots_completed: { title: "Провідник Основ", description: "Завершіть чотири корені гілок." },
    awakening_trial_completed: { title: "Випробування пробудження", description: "Завершіть випробування глави Foundation." },
    beta_tester_account: { title: "Засновник закритої бети", description: "Створіть підтверджений акаунт Habidoo під час закритої бети." }
  }
};

export function gameShellT(locale: Locale, key: string) {
  return copy[locale]?.[key] ?? copy.en[key] ?? key;
}

export function itemText(locale: Locale, item: { id: string; title: string; description: string }) {
  return itemCopy[locale]?.[item.id] ?? { title: item.title, description: item.description };
}

export function achievementText(locale: Locale, achievement: { id: string; title: string; description: string }) {
  return achievementCopy[locale]?.[achievement.id] ?? { title: achievement.title, description: achievement.description };
}
