import { LifeTechnology } from "./types";

export const categoryLabels = {
  health: "Health",
  mind: "Mind",
  career: "Career",
  business: "Business",
  finance: "Finance",
  relationships: "Relationships",
  creativity: "Creativity"
};

export const categoryColors = {
  health: "#74d680",
  mind: "#9b7cff",
  career: "#4ce0d2",
  business: "#f6c453",
  finance: "#55b8ff",
  relationships: "#ff8ab3",
  creativity: "#ff9f5a"
};

export const technologies: LifeTechnology[] = [
  {
    id: "health-root",
    category: "health",
    title: "Body Awareness",
    description: "Start treating your body like a core civilization system.",
    xpReward: 50,
    requirements: [{ label: "Complete 1 health mission", current: 0, target: 1 }],
    parents: [],
    unlocks: ["morning-walk", "hydration"],
    x: 120,
    y: 150
  },
  {
    id: "morning-walk",
    category: "health",
    title: "Morning Walk",
    description: "Build the first outdoor movement ritual.",
    xpReward: 80,
    requirements: [{ label: "Walk 3 mornings", current: 1, target: 3 }],
    parents: ["health-root"],
    unlocks: ["cardio-i"],
    x: 360,
    y: 70
  },
  {
    id: "hydration",
    category: "health",
    title: "Hydration Protocol",
    description: "Stabilize energy by making water automatic.",
    xpReward: 70,
    requirements: [{ label: "Drink water 5 days", current: 2, target: 5 }],
    parents: ["health-root"],
    unlocks: ["strength-training"],
    x: 360,
    y: 230
  },
  {
    id: "cardio-i",
    category: "health",
    title: "Cardio I",
    description: "Unlock basic endurance through repeated sessions.",
    xpReward: 120,
    requirements: [{ label: "Complete 5 workouts", current: 0, target: 5 }],
    parents: ["morning-walk"],
    unlocks: ["athlete"],
    x: 620,
    y: 70
  },
  {
    id: "strength-training",
    category: "health",
    title: "Strength Training",
    description: "Add resistance work as a long-term body upgrade.",
    xpReward: 140,
    requirements: [{ label: "Complete 8 strength sessions", current: 0, target: 8 }],
    parents: ["hydration"],
    unlocks: ["athlete"],
    x: 620,
    y: 230
  },
  {
    id: "athlete",
    category: "health",
    title: "Athlete",
    description: "Combine movement, endurance, and strength into identity.",
    xpReward: 300,
    requirements: [{ label: "Unlock Cardio I and Strength Training", current: 0, target: 2 }],
    parents: ["cardio-i", "strength-training"],
    unlocks: [],
    x: 900,
    y: 150
  },
  {
    id: "mind-root",
    category: "mind",
    title: "Mental Clarity",
    description: "Create space for deliberate thinking before the day controls you.",
    xpReward: 50,
    requirements: [{ label: "Complete 1 mind mission", current: 0, target: 1 }],
    parents: [],
    unlocks: ["reader", "deep-work"],
    x: 120,
    y: 500
  },
  {
    id: "reader",
    category: "mind",
    title: "Reader",
    description: "Build a knowledge base through consistent reading.",
    xpReward: 130,
    requirements: [{ label: "Read 500 pages", current: 80, target: 500 }],
    parents: ["mind-root"],
    unlocks: ["systems-thinker"],
    x: 390,
    y: 420
  },
  {
    id: "deep-work",
    category: "mind",
    title: "Deep Work I",
    description: "Protect attention for one meaningful session.",
    xpReward: 120,
    requirements: [{ label: "Complete 5 focus sessions", current: 1, target: 5 }],
    parents: ["mind-root"],
    unlocks: ["systems-thinker"],
    x: 390,
    y: 580
  },
  {
    id: "systems-thinker",
    category: "mind",
    title: "Systems Thinker",
    description: "Connect knowledge, attention, and decisions into a repeatable system.",
    xpReward: 320,
    requirements: [{ label: "Unlock Reader and Deep Work", current: 0, target: 2 }],
    parents: ["reader", "deep-work"],
    unlocks: [],
    x: 690,
    y: 500
  },
  {
    id: "business-root",
    category: "business",
    title: "Builder Mindset",
    description: "Start creating assets instead of only consuming information.",
    xpReward: 60,
    requirements: [{ label: "Finish 1 builder mission", current: 0, target: 1 }],
    parents: [],
    unlocks: ["first-project"],
    x: 120,
    y: 850
  },
  {
    id: "first-project",
    category: "business",
    title: "First Project",
    description: "Ship a small project that can be shown to real people.",
    xpReward: 120,
    requirements: [{ label: "Complete 5 project sessions", current: 2, target: 5 }],
    parents: ["business-root"],
    unlocks: ["mvp-launch"],
    x: 380,
    y: 850
  },
  {
    id: "mvp-launch",
    category: "business",
    title: "MVP Launch",
    description: "Publish a minimal product and collect real feedback.",
    xpReward: 220,
    requirements: [{ label: "Launch 1 MVP", current: 0, target: 1 }],
    parents: ["first-project"],
    unlocks: ["first-paying-user", "one-hundred-users"],
    x: 650,
    y: 850
  },
  {
    id: "first-paying-user",
    category: "business",
    title: "First Paying User",
    description: "Validate that someone will pay for what you built.",
    xpReward: 400,
    requirements: [{ label: "Get 1 paid customer", current: 0, target: 1 }],
    parents: ["mvp-launch"],
    unlocks: ["founder"],
    x: 930,
    y: 770
  },
  {
    id: "one-hundred-users",
    category: "business",
    title: "100 Users",
    description: "Prove that the product can attract repeated attention.",
    xpReward: 450,
    requirements: [{ label: "Reach 100 users", current: 0, target: 100 }],
    parents: ["mvp-launch"],
    unlocks: ["founder"],
    x: 930,
    y: 930
  },
  {
    id: "founder",
    category: "business",
    title: "Founder",
    description: "Move from project mode to company-building mode.",
    xpReward: 700,
    requirements: [{ label: "Unlock traction milestones", current: 0, target: 2 }],
    parents: ["first-paying-user", "one-hundred-users"],
    unlocks: [],
    x: 1210,
    y: 850
  },
  {
    id: "career-root",
    category: "career",
    title: "Career Direction",
    description: "Define a professional vector instead of drifting between tasks.",
    xpReward: 60,
    requirements: [{ label: "Choose 1 career focus", current: 0, target: 1 }],
    parents: [],
    unlocks: ["portfolio", "interview-ready"],
    x: 120,
    y: 1200
  },
  {
    id: "portfolio",
    category: "career",
    title: "Proof Portfolio",
    description: "Create visible evidence of what you can do.",
    xpReward: 160,
    requirements: [{ label: "Publish 3 proof items", current: 0, target: 3 }],
    parents: ["career-root"],
    unlocks: ["career-upgrade"],
    x: 400,
    y: 1120
  },
  {
    id: "interview-ready",
    category: "career",
    title: "Interview Ready",
    description: "Prepare a clear story about skills, results, and direction.",
    xpReward: 150,
    requirements: [{ label: "Practice 5 answers", current: 0, target: 5 }],
    parents: ["career-root"],
    unlocks: ["career-upgrade"],
    x: 400,
    y: 1280
  },
  {
    id: "career-upgrade",
    category: "career",
    title: "Career Upgrade",
    description: "Use proof and preparation to unlock a better professional position.",
    xpReward: 420,
    requirements: [{ label: "Complete portfolio and interview prep", current: 0, target: 2 }],
    parents: ["portfolio", "interview-ready"],
    unlocks: [],
    x: 720,
    y: 1200
  },
  {
    id: "finance-root",
    category: "finance",
    title: "Money Map",
    description: "See where money goes before trying to optimize it.",
    xpReward: 60,
    requirements: [{ label: "Track 7 days", current: 0, target: 7 }],
    parents: [],
    unlocks: ["emergency-fund", "first-investment"],
    x: 120,
    y: 1550
  },
  {
    id: "emergency-fund",
    category: "finance",
    title: "Emergency Fund",
    description: "Build a financial shield against chaos.",
    xpReward: 200,
    requirements: [{ label: "Save first buffer", current: 0, target: 1 }],
    parents: ["finance-root"],
    unlocks: ["financial-independence"],
    x: 410,
    y: 1470
  },
  {
    id: "first-investment",
    category: "finance",
    title: "First Investment",
    description: "Move from saving only to building future assets.",
    xpReward: 220,
    requirements: [{ label: "Create first portfolio", current: 0, target: 1 }],
    parents: ["finance-root"],
    unlocks: ["financial-independence"],
    x: 410,
    y: 1630
  },
  {
    id: "financial-independence",
    category: "finance",
    title: "Financial Independence",
    description: "Long-term branch for freedom, optionality, and resilience.",
    xpReward: 900,
    requirements: [{ label: "Unlock fund and investing systems", current: 0, target: 2 }],
    parents: ["emergency-fund", "first-investment"],
    unlocks: [],
    x: 760,
    y: 1550
  },
  {
    id: "relationships-root",
    category: "relationships",
    title: "Social Signal",
    description: "Make relationships an intentional part of the life strategy.",
    xpReward: 50,
    requirements: [{ label: "Reach out once", current: 0, target: 1 }],
    parents: [],
    unlocks: ["weekly-check-in"],
    x: 120,
    y: 1900
  },
  {
    id: "weekly-check-in",
    category: "relationships",
    title: "Weekly Check-in",
    description: "Create a rhythm of connection with people who matter.",
    xpReward: 140,
    requirements: [{ label: "Complete 4 check-ins", current: 0, target: 4 }],
    parents: ["relationships-root"],
    unlocks: ["trusted-circle"],
    x: 410,
    y: 1900
  },
  {
    id: "trusted-circle",
    category: "relationships",
    title: "Trusted Circle",
    description: "Develop a small network of mutual support and accountability.",
    xpReward: 340,
    requirements: [{ label: "Build 3 consistent connections", current: 0, target: 3 }],
    parents: ["weekly-check-in"],
    unlocks: [],
    x: 720,
    y: 1900
  },
  {
    id: "creativity-root",
    category: "creativity",
    title: "Creative Spark",
    description: "Start turning ideas into visible creative output.",
    xpReward: 50,
    requirements: [{ label: "Capture 5 ideas", current: 1, target: 5 }],
    parents: [],
    unlocks: ["daily-output"],
    x: 120,
    y: 2250
  },
  {
    id: "daily-output",
    category: "creativity",
    title: "Daily Output",
    description: "Practice publishing or finishing small creative pieces.",
    xpReward: 160,
    requirements: [{ label: "Create 7 outputs", current: 0, target: 7 }],
    parents: ["creativity-root"],
    unlocks: ["creative-identity"],
    x: 410,
    y: 2250
  },
  {
    id: "creative-identity",
    category: "creativity",
    title: "Creative Identity",
    description: "Become someone who repeatedly turns ideas into artifacts.",
    xpReward: 380,
    requirements: [{ label: "Finish 3 meaningful artifacts", current: 0, target: 3 }],
    parents: ["daily-output"],
    unlocks: [],
    x: 720,
    y: 2250
  }
];
