import type { Locale, MissionDefinition, UserFocusObject } from "./types";

type MissionTranslation = {
  actionTitle: string;
  concreteOutcome: string;
  recommendedChoice: string;
  exampleResult: string;
  inputs: Record<string, { label: string; placeholder?: string; example?: string }>;
  choices?: Record<string, string>;
  steps?: string[];
};

const ru: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Сделайте маленький телесный сброс", concreteOutcome: "Вода, дыхание и 60 секунд растяжки шеи или плеч выполнены до сохранения результата.", recommendedChoice: "Встаньте, выпейте воды, сделайте 10 медленных вдохов и 60 секунд потяните плечи или шею.", exampleResult: "Действие выполнено; энергия 3/5; сигнал тела: шея напряжена после сидения.", inputs: { "body-reset-completed": { label: "Я встал, выпил воды, медленно подышал и растянулся 60 секунд." }, "energy-after": { label: "Энергия после сброса" }, "body-factor": { label: "Один сигнал тела, который вы заметили", placeholder: "Например: напряжённая шея после сидения" } } },
  "mind-root": { actionTitle: "Уберите лишнее и выберите следующий физический шаг", concreteOutcome: "Одна помеха убрана, сохранено действие, которое можно начать на 5 минут.", recommendedChoice: "Закройте лишние вкладки или приложения, уберите одну видимую помеху и выберите задачу на 5 минут.", exampleResult: "Открыть файл страницы регистрации и закончить поле email.", inputs: { "workspace-cleared": { label: "Я закрыл лишние вкладки, приложения и материалы." }, "next-step": { label: "Какое физическое действие вы сделаете следующим?", placeholder: "Открыть… / Отправить… / Завершить…" } } },
  "finance-root": { actionTitle: "Откройте денежный источник и сохраните базовый снимок", concreteOutcome: "Банк, заметки или таблица открыты; четыре базовых числа или регулярный платёж записаны.", recommendedChoice: "Откройте один денежный источник сейчас и используйте приблизительные числа, если точные нельзя найти за две минуты.", exampleResult: "Открыл банк; баланс 1200; доход 2100; постоянные 1250; переменные 500.", inputs: { balance: { label: "Доступный баланс" }, income: { label: "Ожидаемый доход за месяц" }, "fixed-costs": { label: "Постоянные расходы за месяц" }, "flexible-spending": { label: "Ожидаемые переменные расходы" }, "money-source-opened": { label: "Я открыл банк, заметки или таблицу перед сохранением снимка." } } },
  "business-root": { actionTitle: "Откройте файл проекта и создайте маленький артефакт", concreteOutcome: "Реальная поверхность проекта открыта, один видимый артефакт или изменение существует.", recommendedChoice: "Откройте проект, ближайший к полезной версии, и создайте самое маленькое видимое изменение.", exampleResult: "Открыл заметки Habidoo; добавил черновой чеклист экрана регистрации.", inputs: { "project-type": { label: "Над чем будем работать?" }, "project-name": { label: "Название проекта", placeholder: "Например: мой проект" }, "desired-result": { label: "Какой видимый результат должен появиться?" }, "visible-artifact": { label: "Какой маленький видимый артефакт существует сейчас?", placeholder: "Например: план, черновик, экран, чеклист" } }, choices: { "site-app": "Сайт или приложение", "document-process": "Рабочий документ или процесс", "service-business": "Услуга или бизнес-идея", "creative-project": "Творческий проект" } },
  "career-root": { actionTitle: "Сохраните возможность или обновите карьерную поверхность", concreteOutcome: "Целевая роль и один сохранённый карьерный элемент теперь существуют.", recommendedChoice: "Сохраните реалистичную роль/возможность или обновите одну строку резюме, профиля или портфолио.", exampleResult: "Frontend-разработчик; сохранена React-вакансия и обновлена строка портфолио.", inputs: { "career-target": { label: "Какая карьерная цель сейчас ближе всего?" }, "career-saved-item": { label: "Что вы сохранили или обновили?", placeholder: "Ссылка на роль, строка CV, профиль или портфолио" } }, choices: { "prove-skill": "Создать доказательство навыка", "improve-profile": "Улучшить резюме или профиль", "learn-skill": "Освоить полезный для роли навык", "explore-role": "Изучить реалистичную новую роль" } },
  "relationships-root": { actionTitle: "Отправьте или подготовьте содержательное сообщение", concreteOutcome: "Реальный человек, способ контакта и следующий шаг сохранены после конкретного действия.", recommendedChoice: "Отправьте сообщение, если уместно; иначе сохраните готовый черновик.", exampleResult: "Анна — подготовлен конкретный check-in в WhatsApp; следующий шаг: отправить вечером.", inputs: { "person-name": { label: "Имя человека", placeholder: "Например: Анна" }, "contact-method": { label: "Где вы отправили или подготовили сообщение?" }, "connection-outcome": { label: "Какой следующий шаг?", placeholder: "Отправить вечером / дождаться ответа / предложить звонок" } }, choices: { message: "Мессенджер или SMS", email: "Email", call: "Заметка к звонку", social: "Социальное приложение" } },
  "creativity-root": { actionTitle: "Создайте черновик за 10 минут", concreteOutcome: "Творческий формат выбран, и грубый сохранённый артефакт уже существует.", recommendedChoice: "Используйте формат с минимальной подготовкой и остановитесь на грубой первой версии.", exampleResult: "Текст — черновой первый абзац сохранён в заметках.", inputs: { "creative-medium": { label: "Какой формат вы использовали?" }, "draft-created": { label: "Я создал и сохранил грубый 10-минутный черновик." }, "draft-result": { label: "Что существует сейчас?", placeholder: "Черновой абзац, скетч, клип, мелодия…" } }, choices: { writing: "Текст", "drawing-design": "Рисунок или дизайн", "photo-video": "Фото или видео", "music-audio": "Музыка или аудио" } },
  "morning-walk": { actionTitle: "Пройдитесь на улице 10 минут", concreteOutcome: "Сохранены реальная десятиминутная прогулка и изменение энергии.", recommendedChoice: "Пройдите самый простой знакомый маршрут, не думая о расстоянии и темпе.", exampleResult: "Прогулка завершена; энергия изменилась с 2/5 до 3/5.", inputs: { "walk-completed": { label: "Я гулял на улице не менее 10 минут." }, "energy-after": { label: "Энергия после прогулки" } } },
  "reading-ritual": { actionTitle: "Прочитайте один подготовленный источник и сохраните полезную идею", concreteOutcome: "Один источник прочитан, одна применимая идея сохранена.", recommendedChoice: "Продолжите уже начатый источник вместо поиска нового.", exampleResult: "Прочитано 10 страниц; сохранена идея уменьшить подготовку перед фокусной работой.", inputs: { "reading-choice": { label: "Что вы читали?" }, "key-idea": { label: "Какую полезную идею вы сохраните?", placeholder: "Одно предложение для будущего применения" } }, choices: { book: "Уже начатая книга", article: "Одна сохранённая статья", "course-note": "Заметки курса или урока" } },
  "expense-tracking": { actionTitle: "Запишите все сегодняшние платежи", concreteOutcome: "Сохранены платежи за сегодня и крупнейшая категория расходов.", recommendedChoice: "Используйте историю банка и добавьте наличные покупки, которые помните.", exampleResult: "Записано 6 платежей; крупнейшая категория — еда.", inputs: { "payment-count": { label: "Сколько платежей вы записали?" }, "largest-category": { label: "Какая категория была крупнейшей?" } }, choices: { housing: "Жильё", food: "Еда", transport: "Транспорт", subscriptions: "Подписки" } },
  "project-definition": { actionTitle: "Определите один видимый результат и одну границу", concreteOutcome: "Сохранены следующий результат и то, что не входит в его объём.", recommendedChoice: "Выберите самый маленький результат, который другой человек сможет увидеть или использовать.", exampleResult: "Экран регистрации; оплата и настройки аккаунта не входят в эту версию.", inputs: { deliverable: { label: "Что станет видимым?" }, boundary: { label: "Что точно не входит в эту версию?", placeholder: "Не входит в эту версию…" } }, choices: { screen: "Один рабочий экран", document: "Один завершённый раздел документа", process: "Один применимый процесс", prototype: "Один демонстрируемый прототип" } },
  "opportunity-scan": { actionTitle: "Сохраните одну реалистичную профессиональную возможность", concreteOutcome: "Сохранены целевая роль и одна конкретная возможность.", recommendedChoice: "Выберите возможность, которая совпадает хотя бы с половиной ваших текущих навыков.", exampleResult: "Frontend-разработчик; сохранена роль с React и базовым тестированием.", inputs: { "target-role": { label: "Какую роль или направление вы изучаете?" }, "opportunity-source": { label: "Где вы нашли возможность?" }, "saved-opportunity": { label: "Какую возможность вы сохранили?", placeholder: "Роль, проект или следующий контакт" } }, choices: { job: "Вакансия", project: "Проект или фриланс-запрос", person: "Разговор или рекомендация" } },
  "weekly-check-in": { actionTitle: "Свяжитесь с человеком по-настоящему", concreteOutcome: "Сохранены один осознанный контакт и его результат.", recommendedChoice: "Отправьте короткое конкретное сообщение человеку, уже выбранному как фокус.", exampleResult: "Написал Анне; договорились созвониться в пятницу.", inputs: { "contact-method": { label: "Как вы связались?" }, "contact-result": { label: "Что произошло после контакта?", placeholder: "Один конкретный ответ или следующий шаг" } }, choices: { message: "Содержательное сообщение", call: "Короткий звонок", meeting: "Встреча назначена или состоялась" } },
  "reference-study": { actionTitle: "Изучите один пример и выделите один принцип", concreteOutcome: "Сохранены один пример и один принцип для собственной работы.", recommendedChoice: "Используйте уже знакомый сильный пример вместо поиска идеального.", exampleResult: "Изучена посадочная страница; сохранён принцип одного ясного действия на раздел.", inputs: { "reference-type": { label: "Какой пример вы изучали?" }, principle: { label: "Какой принцип вы попробуете в своей работе?", placeholder: "Один конкретный принцип" } }, choices: { article: "Статья или текст", design: "Дизайн или иллюстрация", video: "Видео или фото", book: "Книга или большая работа" } }
};

const cs: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Start маленький телесный сброс", concreteOutcome: "Вода, дыхание и 60 секунд растяжки шеи или плеч выполнены до сохранения результата.", recommendedChoice: "Встаньте, выпейте воды, сделайте 10 медленных вдохов и 60 секунд потяните плечи или шею.", exampleResult: "Действие выполнено; энергия 3/5; сигнал тела: шея напряжена после сидения.", inputs: { "body-reset-completed": { label: "Я встал, выпил воды, медленно подышал и растянулся 60 секунд." }, "energy-after": { label: "Энергия после сброса" }, "body-factor": { label: "Один сигнал тела, который вы заметили", placeholder: "Например: напряжённая шея после сидения" } } },
  "mind-root": { actionTitle: "Уберите лишнее и выберите следующий физический шаг", concreteOutcome: "Одна помеха убрана, сохранено действие, которое можно начать на 5 минут.", recommendedChoice: "Закройте лишние вкладки или приложения, уберите одну видимую помеху и выберите задачу на 5 минут.", exampleResult: "Открыть файл страницы регистрации и закончить поле email.", inputs: { "workspace-cleared": { label: "Я закрыл лишние вкладки, приложения и материалы." }, "next-step": { label: "Какое физическое действие вы сделаете следующим?", placeholder: "Открыть… / Отправить… / Завершить…" } } },
  "finance-root": { actionTitle: "Open денежный источник и сохраните базовый снимок", concreteOutcome: "Банк, заметки или таблица открыты; четыре базовых числа или регулярный платёж записаны.", recommendedChoice: "Open один денежный источник сейчас и используйте приблизительные числа, если точные нельзя найти за две минуты.", exampleResult: "Открыл банк; баланс 1200; доход 2100; постоянные 1250; переменные 500.", inputs: { balance: { label: "Доступный баланс" }, income: { label: "Ожидаемый доход за месяц" }, "fixed-costs": { label: "Постоянные расходы за месяц" }, "flexible-spending": { label: "Ожидаемые переменные расходы" }, "money-source-opened": { label: "Я открыл банк, заметки или таблицу перед сохранением снимка." } } },
  "business-root": { actionTitle: "Open файл проекта и создайте маленький артефакт", concreteOutcome: "Реальная поверхность проекта открыта, один видимый артефакт или изменение существует.", recommendedChoice: "Open проект, ближайший к полезной версии, и создайте самое маленькое видимое изменение.", exampleResult: "Открыл заметки Habidoo; добавил черновой чеклист экрана регистрации.", inputs: { "project-type": { label: "Над чем будем работать?" }, "project-name": { label: "Название проекта", placeholder: "Например: мой проект" }, "desired-result": { label: "Какой видимый результат должен появиться?" }, "visible-artifact": { label: "Какой маленький видимый артефакт существует сейчас?", placeholder: "Например: план, черновик, экран, чеклист" } }, choices: { "site-app": "Сайт или приложение", "document-process": "Рабочий документ или процесс", "service-business": "Услуга или бизнес-идея", "creative-project": "Творческий проект" } },
  "career-root": { actionTitle: "Save возможность или обновите карьерную поверхность", concreteOutcome: "Целевая роль и один сохранённый карьерный элемент теперь существуют.", recommendedChoice: "Save реалистичную роль/возможность или обновите одну строку резюме, профиля или портфолио.", exampleResult: "Frontend-разработчик; сохранена React-вакансия и обновлена строка портфолио.", inputs: { "career-target": { label: "Какая карьерная цель сейчас ближе всего?" }, "career-saved-item": { label: "Что вы сохранили или обновили?", placeholder: "Ссылка на роль, строка CV, профиль или портфолио" } }, choices: { "prove-skill": "Создать доказательство навыка", "improve-profile": "Улучшить резюме или профиль", "learn-skill": "Освоить полезный для роли навык", "explore-role": "Изучить реалистичную новую роль" } },
  "relationships-root": { actionTitle: "Send или подготовьте содержательное сообщение", concreteOutcome: "Реальный человек, способ контакта и следующий шаг сохранены после конкретного действия.", recommendedChoice: "Send сообщение, если уместно; иначе сохраните готовый черновик.", exampleResult: "Анна — подготовлен конкретный check-in в WhatsApp; следующий шаг: отправить вечером.", inputs: { "person-name": { label: "Имя человека", placeholder: "Например: Анна" }, "contact-method": { label: "Где вы отправили или подготовили сообщение?" }, "connection-outcome": { label: "Какой следующий шаг?", placeholder: "Отправить вечером / дождаться ответа / предложить звонок" } }, choices: { message: "Мессенджер или SMS", email: "Email", call: "Заметка к звонку", social: "Социальное приложение" } },
  "creativity-root": { actionTitle: "Create черновик за 10 минут", concreteOutcome: "Творческий формат выбран, и грубый сохранённый артефакт уже существует.", recommendedChoice: "Используйте формат с минимальной подготовкой и остановитесь на грубой первой версии.", exampleResult: "Текст — черновой первый абзац сохранён в заметках.", inputs: { "creative-medium": { label: "Какой формат вы использовали?" }, "draft-created": { label: "Я создал и сохранил грубый 10-минутный черновик." }, "draft-result": { label: "Что существует сейчас?", placeholder: "Черновой абзац, скетч, клип, мелодия…" } }, choices: { writing: "Текст", "drawing-design": "Рисунок или дизайн", "photo-video": "Фото или видео", "music-audio": "Музыка или аудио" } },
  "morning-walk": { actionTitle: "Jděte deset minut venku", concreteOutcome: "Je zaznamenána skutečná desetiminutová procházka a změna energie.", recommendedChoice: "Zvolte nejjednodušší známou trasu bez řešení vzdálenosti a tempa.", exampleResult: "Procházka dokončena; energie se změnila z 2/5 na 3/5.", inputs: { "walk-completed": { label: "Šel/šla jsem venku alespoň 10 minut." }, "energy-after": { label: "Energie po procházce" } }, steps: ["Vyjděte ven.", "Jděte alespoň deset minut.", "Ohodnoťte energii po návratu."] },
  "reading-ritual": { actionTitle: "Přečtěte jeden připravený zdroj a uložte užitečnou myšlenku", concreteOutcome: "Jeden zdroj je přečten a jedna použitelná myšlenka uložena.", recommendedChoice: "Pokračujte v již rozečteném zdroji místo hledání nového.", exampleResult: "Přečteno 10 stran; uložena myšlenka zmenšit přípravu před soustředěnou prací.", inputs: { "reading-choice": { label: "Co jste četli?" }, "key-idea": { label: "Jakou užitečnou myšlenku si ponecháte?", placeholder: "Jedna věta pro další použití" } }, choices: { book: "Rozečtená kniha", article: "Jeden uložený článek", "course-note": "Poznámky z kurzu nebo lekce" }, steps: ["Vyberte již připravený zdroj.", "Čtěte soustředěně.", "Uložte jednu použitelnou myšlenku."] },
  "expense-tracking": { actionTitle: "Zapište všechny dnešní platby", concreteOutcome: "Dnešní platby a největší kategorie výdajů jsou uloženy.", recommendedChoice: "Použijte historii banky a přidejte hotovostní nákupy, na které si vzpomenete.", exampleResult: "Zaznamenáno 6 plateb; největší kategorií bylo jídlo.", inputs: { "payment-count": { label: "Kolik plateb jste zaznamenali?" }, "largest-category": { label: "Která kategorie byla největší?" } }, choices: { housing: "Bydlení", food: "Jídlo", transport: "Doprava", subscriptions: "Předplatné" }, steps: ["Otevřete historii plateb.", "Zapište dnešní platby.", "Určete největší kategorii."] },
  "project-definition": { actionTitle: "Určete jeden viditelný výstup a jednu hranici", concreteOutcome: "Další výstup a to, co je mimo jeho rozsah, jsou uloženy.", recommendedChoice: "Zvolte nejmenší výstup, který může někdo jiný vidět nebo použít.", exampleResult: "Registrační obrazovka; platby a nastavení účtu nejsou součástí této verze.", inputs: { deliverable: { label: "Co bude viditelné?" }, boundary: { label: "Co výslovně není součástí této verze?", placeholder: "Není součástí této verze…" } }, choices: { screen: "Jedna funkční obrazovka", document: "Jedna hotová část dokumentu", process: "Jeden použitelný proces", prototype: "Jeden ukázkový prototyp" }, steps: ["Zvolte jeden viditelný výstup.", "Popište jeho minimální užitečnou verzi.", "Uložte jednu jasnou hranici."] },
  "opportunity-scan": { actionTitle: "Uložte jednu realistickou profesní příležitost", concreteOutcome: "Cílová role a jedna konkrétní příležitost jsou uloženy.", recommendedChoice: "Zvolte příležitost odpovídající alespoň polovině vašich současných dovedností.", exampleResult: "Frontend vývojář; uložena role vyžadující React a základní testování.", inputs: { "target-role": { label: "Jakou roli nebo směr zkoumáte?" }, "opportunity-source": { label: "Kde jste příležitost našli?" }, "saved-opportunity": { label: "Jakou příležitost jste uložili?", placeholder: "Role, projekt nebo další kontakt" } }, choices: { job: "Pracovní nabídka", project: "Projekt nebo freelance poptávka", person: "Rozhovor nebo doporučení" }, steps: ["Zvolte cílovou roli.", "Najděte jednu realistickou příležitost.", "Uložte ji pro další krok."] },
  "weekly-check-in": { actionTitle: "Proveďte jeden opravdový kontakt", concreteOutcome: "Jeden vědomý kontakt a jeho výsledek jsou zaznamenány.", recommendedChoice: "Pošlete krátkou konkrétní zprávu osobě zvolenému jako zaměření.", exampleResult: "Napsal/a jsem Anně; domluvili jsme si páteční hovor.", inputs: { "contact-method": { label: "Jak jste se spojili?" }, "contact-result": { label: "Co se stalo po kontaktu?", placeholder: "Jedna konkrétní odpověď nebo další krok" } }, choices: { message: "Smysluplná zpráva", call: "Krátký hovor", meeting: "Domluvené nebo uskutečněné setkání" }, steps: ["Vyberte osobu ze svého zaměření.", "Proveďte jeden opravdový kontakt.", "Uložte výsledek nebo další krok."] },
  "reference-study": { actionTitle: "Prostudujte jednu referenci a vyberte jeden princip", concreteOutcome: "Jedna reference a jeden princip pro vlastní práci jsou uloženy.", recommendedChoice: "Použijte referenci, kterou již obdivujete, místo hledání dokonalého příkladu.", exampleResult: "Prostudována vstupní stránka; uložen princip jedné jasné akce v každé části.", inputs: { "reference-type": { label: "Jakou referenci jste studovali?" }, principle: { label: "Jaký princip vyzkoušíte ve vlastní práci?", placeholder: "Jeden konkrétní princip" } }, choices: { article: "Článek nebo text", design: "Design nebo ilustrace", video: "Video nebo fotografie", book: "Kniha nebo delší dílo" }, steps: ["Vyberte jednu silnou referenci.", "Najděte tři rozhodnutí autora.", "Uložte jeden princip pro vlastní práci."] }
};

const uk: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Start маленький телесный сброс", concreteOutcome: "Вода, дыхание и 60 секунд растяжки шеи или плеч выполнены до сохранения результата.", recommendedChoice: "Встаньте, выпейте воды, сделайте 10 медленных вдохов и 60 секунд потяните плечи или шею.", exampleResult: "Действие выполнено; энергия 3/5; сигнал тела: шея напряжена после сидения.", inputs: { "body-reset-completed": { label: "Я встал, выпил воды, медленно подышал и растянулся 60 секунд." }, "energy-after": { label: "Энергия после сброса" }, "body-factor": { label: "Один сигнал тела, который вы заметили", placeholder: "Например: напряжённая шея после сидения" } } },
  "mind-root": { actionTitle: "Уберите лишнее и выберите следующий физический шаг", concreteOutcome: "Одна помеха убрана, сохранено действие, которое можно начать на 5 минут.", recommendedChoice: "Закройте лишние вкладки или приложения, уберите одну видимую помеху и выберите задачу на 5 минут.", exampleResult: "Открыть файл страницы регистрации и закончить поле email.", inputs: { "workspace-cleared": { label: "Я закрыл лишние вкладки, приложения и материалы." }, "next-step": { label: "Какое физическое действие вы сделаете следующим?", placeholder: "Открыть… / Отправить… / Завершить…" } } },
  "finance-root": { actionTitle: "Open денежный источник и сохраните базовый снимок", concreteOutcome: "Банк, заметки или таблица открыты; четыре базовых числа или регулярный платёж записаны.", recommendedChoice: "Open один денежный источник сейчас и используйте приблизительные числа, если точные нельзя найти за две минуты.", exampleResult: "Открыл банк; баланс 1200; доход 2100; постоянные 1250; переменные 500.", inputs: { balance: { label: "Доступный баланс" }, income: { label: "Ожидаемый доход за месяц" }, "fixed-costs": { label: "Постоянные расходы за месяц" }, "flexible-spending": { label: "Ожидаемые переменные расходы" }, "money-source-opened": { label: "Я открыл банк, заметки или таблицу перед сохранением снимка." } } },
  "business-root": { actionTitle: "Open файл проекта и создайте маленький артефакт", concreteOutcome: "Реальная поверхность проекта открыта, один видимый артефакт или изменение существует.", recommendedChoice: "Open проект, ближайший к полезной версии, и создайте самое маленькое видимое изменение.", exampleResult: "Открыл заметки Habidoo; добавил черновой чеклист экрана регистрации.", inputs: { "project-type": { label: "Над чем будем работать?" }, "project-name": { label: "Название проекта", placeholder: "Например: мой проект" }, "desired-result": { label: "Какой видимый результат должен появиться?" }, "visible-artifact": { label: "Какой маленький видимый артефакт существует сейчас?", placeholder: "Например: план, черновик, экран, чеклист" } }, choices: { "site-app": "Сайт или приложение", "document-process": "Рабочий документ или процесс", "service-business": "Услуга или бизнес-идея", "creative-project": "Творческий проект" } },
  "career-root": { actionTitle: "Save возможность или обновите карьерную поверхность", concreteOutcome: "Целевая роль и один сохранённый карьерный элемент теперь существуют.", recommendedChoice: "Save реалистичную роль/возможность или обновите одну строку резюме, профиля или портфолио.", exampleResult: "Frontend-разработчик; сохранена React-вакансия и обновлена строка портфолио.", inputs: { "career-target": { label: "Какая карьерная цель сейчас ближе всего?" }, "career-saved-item": { label: "Что вы сохранили или обновили?", placeholder: "Ссылка на роль, строка CV, профиль или портфолио" } }, choices: { "prove-skill": "Создать доказательство навыка", "improve-profile": "Улучшить резюме или профиль", "learn-skill": "Освоить полезный для роли навык", "explore-role": "Изучить реалистичную новую роль" } },
  "relationships-root": { actionTitle: "Send или подготовьте содержательное сообщение", concreteOutcome: "Реальный человек, способ контакта и следующий шаг сохранены после конкретного действия.", recommendedChoice: "Send сообщение, если уместно; иначе сохраните готовый черновик.", exampleResult: "Анна — подготовлен конкретный check-in в WhatsApp; следующий шаг: отправить вечером.", inputs: { "person-name": { label: "Имя человека", placeholder: "Например: Анна" }, "contact-method": { label: "Где вы отправили или подготовили сообщение?" }, "connection-outcome": { label: "Какой следующий шаг?", placeholder: "Отправить вечером / дождаться ответа / предложить звонок" } }, choices: { message: "Мессенджер или SMS", email: "Email", call: "Заметка к звонку", social: "Социальное приложение" } },
  "creativity-root": { actionTitle: "Create черновик за 10 минут", concreteOutcome: "Творческий формат выбран, и грубый сохранённый артефакт уже существует.", recommendedChoice: "Используйте формат с минимальной подготовкой и остановитесь на грубой первой версии.", exampleResult: "Текст — черновой первый абзац сохранён в заметках.", inputs: { "creative-medium": { label: "Какой формат вы использовали?" }, "draft-created": { label: "Я создал и сохранил грубый 10-минутный черновик." }, "draft-result": { label: "Что существует сейчас?", placeholder: "Черновой абзац, скетч, клип, мелодия…" } }, choices: { writing: "Текст", "drawing-design": "Рисунок или дизайн", "photo-video": "Фото или видео", "music-audio": "Музыка или аудио" } },
  "morning-walk": { actionTitle: "Пройдіться надворі 10 хвилин", concreteOutcome: "Збережено реальну десятихвилинну прогулянку та зміну енергії.", recommendedChoice: "Оберіть найпростіший знайомий маршрут без оптимізації відстані й темпу.", exampleResult: "Прогулянку завершено; енергія змінилася з 2/5 до 3/5.", inputs: { "walk-completed": { label: "Я гуляв/гуляла надворі щонайменше 10 хвилин." }, "energy-after": { label: "Енергія після прогулянки" } }, steps: ["Вийдіть надвір.", "Ідіть щонайменше десять хвилин.", "Оцініть енергію після повернення."] },
  "reading-ritual": { actionTitle: "Прочитайте одне підготовлене джерело й збережіть корисну ідею", concreteOutcome: "Одне джерело прочитано, одну придатну ідею збережено.", recommendedChoice: "Продовжте вже розпочате джерело замість пошуку нового.", exampleResult: "Прочитано 10 сторінок; збережено ідею зменшити підготовку перед фокусною роботою.", inputs: { "reading-choice": { label: "Що ви читали?" }, "key-idea": { label: "Яку корисну ідею ви збережете?", placeholder: "Одне речення для подальшого використання" } }, choices: { book: "Уже розпочата книга", article: "Одна збережена стаття", "course-note": "Нотатки курсу або уроку" }, steps: ["Оберіть уже підготовлене джерело.", "Читайте зосереджено.", "Збережіть одну придатну ідею."] },
  "expense-tracking": { actionTitle: "Запишіть усі сьогоднішні платежі", concreteOutcome: "Сьогоднішні платежі та найбільшу категорію витрат збережено.", recommendedChoice: "Використайте історію банку й додайте готівкові покупки, які пам’ятаєте.", exampleResult: "Записано 6 платежів; найбільша категорія — їжа.", inputs: { "payment-count": { label: "Скільки платежів ви записали?" }, "largest-category": { label: "Яка категорія була найбільшою?" } }, choices: { housing: "Житло", food: "Їжа", transport: "Транспорт", subscriptions: "Підписки" }, steps: ["Відкрийте історію платежів.", "Запишіть сьогоднішні платежі.", "Визначте найбільшу категорію."] },
  "project-definition": { actionTitle: "Визначте один видимий результат і одну межу", concreteOutcome: "Наступний результат і те, що не входить до його обсягу, збережено.", recommendedChoice: "Оберіть найменший результат, який інша людина зможе побачити або використати.", exampleResult: "Екран реєстрації; оплата й налаштування акаунта не входять до цієї версії.", inputs: { deliverable: { label: "Що стане видимим?" }, boundary: { label: "Що точно не входить до цієї версії?", placeholder: "Не входить до цієї версії…" } }, choices: { screen: "Один робочий екран", document: "Один завершений розділ документа", process: "Один придатний процес", prototype: "Один демонстраційний прототип" }, steps: ["Оберіть один видимий результат.", "Опишіть його мінімальну корисну версію.", "Збережіть одну чітку межу."] },
  "opportunity-scan": { actionTitle: "Збережіть одну реалістичну професійну можливість", concreteOutcome: "Цільову роль і одну конкретну можливість збережено.", recommendedChoice: "Оберіть можливість, що відповідає щонайменше половині ваших поточних навичок.", exampleResult: "Frontend-розробник; збережено роль із React і базовим тестуванням.", inputs: { "target-role": { label: "Яку роль або напрям ви досліджуєте?" }, "opportunity-source": { label: "Де ви знайшли можливість?" }, "saved-opportunity": { label: "Яку можливість ви зберегли?", placeholder: "Роль, проєкт або наступний контакт" } }, choices: { job: "Вакансія", project: "Проєкт або фриланс-запит", person: "Розмова або рекомендація" }, steps: ["Оберіть цільову роль.", "Знайдіть одну реалістичну можливість.", "Збережіть її для наступного кроку."] },
  "weekly-check-in": { actionTitle: "Зробіть один справжній контакт", concreteOutcome: "Один свідомий контакт і його результат записано.", recommendedChoice: "Надішліть коротке конкретне повідомлення людині, уже обраній як фокус.", exampleResult: "Написав/написала Анні; домовилися зателефонувати в п’ятницю.", inputs: { "contact-method": { label: "Як ви зв’язалися?" }, "contact-result": { label: "Що сталося після контакту?", placeholder: "Одна конкретна відповідь або наступний крок" } }, choices: { message: "Змістовне повідомлення", call: "Короткий дзвінок", meeting: "Зустріч призначено або проведено" }, steps: ["Оберіть людину зі свого фокусу.", "Зробіть один справжній контакт.", "Збережіть результат або наступний крок."] },
  "reference-study": { actionTitle: "Вивчіть один приклад і виділіть один принцип", concreteOutcome: "Один приклад і один принцип для власної роботи збережено.", recommendedChoice: "Використайте приклад, який уже цінуєте, замість пошуку ідеального.", exampleResult: "Вивчено посадкову сторінку; збережено принцип однієї чіткої дії на розділ.", inputs: { "reference-type": { label: "Який приклад ви вивчали?" }, principle: { label: "Який принцип ви спробуєте у власній роботі?", placeholder: "Один конкретний принцип" } }, choices: { article: "Стаття або текст", design: "Дизайн або ілюстрація", video: "Відео або фото", book: "Книга або велика робота" }, steps: ["Оберіть один сильний приклад.", "Знайдіть три рішення автора.", "Збережіть один принцип для власної роботи."] }
};

export function localizeMissionDefinition(definition: MissionDefinition, locale: Locale): MissionDefinition {
  if (locale === "en") return definition;
  if (definition.technologyId === "awakening-trial") {
    const copy = {
      ru: { actionTitle: "Завершите обзор главы", concreteOutcome: "Итог главы сохраняется из реальных завершённых веток и практик.", recommendedChoice: "Выберите практики, которые вы действительно выполняли и сможете повторять на следующей неделе.", exampleResult: "Сохранены три практики, одно личное правило и недельный стандарт.", inputs: { "reviewed-branches": { label: "Проверенные завершённые ветки" }, "carried-practices": { label: "Три практики, которые берём дальше" }, "personal-rule": { label: "Одно личное правило для следующей главы", placeholder: "Когда происходит X, я делаю Y." }, "weekly-standard": { label: "Реалистичный недельный стандарт", placeholder: "Минимум, который можно повторить в обычную неделю." }, "chapter-confirmed": { label: "Этот итог реалистичен для следующей главы." } } },
      cs: { actionTitle: "Dokončete přehled kapitoly", concreteOutcome: "Souhrn kapitoly se uloží ze skutečně dokončených větví a praxí.", recommendedChoice: "Vyberte praxe, které jste opravdu splnili a dokážete je zopakovat příští týden.", exampleResult: "Uloženy tři praxe, jedno osobní pravidlo a týdenní standard.", inputs: { "reviewed-branches": { label: "Zkontrolované dokončené větve" }, "carried-practices": { label: "Tři praxe pro další kapitolu" }, "personal-rule": { label: "Jedno osobní pravidlo pro další kapitolu", placeholder: "Když nastane X, udělám Y." }, "weekly-standard": { label: "Realistický týdenní standard", placeholder: "Minimum opakovatelné v běžném týdnu." }, "chapter-confirmed": { label: "Tento souhrn je realistický pro další kapitolu." } } },
      uk: { actionTitle: "Завершіть огляд глави", concreteOutcome: "Підсумок глави зберігається з реальних завершених гілок і практик.", recommendedChoice: "Оберіть практики, які ви справді виконували й зможете повторити наступного тижня.", exampleResult: "Збережено три практики, одне особисте правило й тижневий стандарт.", inputs: { "reviewed-branches": { label: "Переглянуті завершені гілки" }, "carried-practices": { label: "Три практики, які беремо далі" }, "personal-rule": { label: "Одне особисте правило для наступної глави", placeholder: "Коли стається X, я роблю Y." }, "weekly-standard": { label: "Реалістичний тижневий стандарт", placeholder: "Мінімум, який можна повторити у звичайний тиждень." }, "chapter-confirmed": { label: "Цей підсумок реалістичний для наступної глави." } } }
    }[locale];
    const inputs = copy.inputs as Record<string, { label: string; placeholder?: string; example?: string }>;
    return { ...definition, ...copy, inputSchema: definition.inputSchema.map((input) => ({ ...input, ...inputs[input.id] })) };
  }
  const translation = (locale === "ru" ? ru : locale === "cs" ? cs : uk)[definition.technologyId];
  if (!translation) {
    const generic = locale === "ru"
      ? { label: "Что стало доступно после этой сессии?", placeholder: "Опишите один видимый результат", recommended: "Завершите минимальную видимую версию, описанную в шагах миссии." }
      : locale === "cs"
        ? { label: "Co je po této relaci dostupné?", placeholder: "Popište jeden viditelný výsledek", recommended: "Dokončete nejmenší viditelnou verzi popsanou v krocích mise." }
        : { label: "Що стало доступним після цієї сесії?", placeholder: "Опишіть один видимий результат", recommended: "Завершіть найменшу видиму версію, описану в кроках місії." };
    return { ...definition, recommendedChoice: generic.recommended, inputSchema: definition.inputSchema.map((input) => input.id === "result" ? { ...input, label: generic.label, placeholder: generic.placeholder } : input) };
  }
  return {
    ...definition,
    actionTitle: translation.actionTitle,
    concreteOutcome: translation.concreteOutcome,
    recommendedChoice: translation.recommendedChoice,
    exampleResult: translation.exampleResult,
    exactSteps: translation.steps ? translation.steps.map((instruction, index) => ({ id: `step-${index + 1}`, instruction })) : definition.exactSteps,
    inputSchema: definition.inputSchema.map((input) => ({
      ...input,
      ...translation.inputs[input.id],
      choices: input.choices?.map((choice) => ({ ...choice, label: translation.choices?.[choice.id] ?? choice.label }))
    }))
  };
}

export function applyFocusObject(definition: MissionDefinition, focusObject: UserFocusObject | undefined, locale: Locale): MissionDefinition {
  if (!focusObject || definition.technologyId.endsWith("-root")) return definition;
  const name = focusObject.name;
  const prefixByType = {
    en: { project: `Use “${name}” as the project context.`, careerSkill: `Use “${name}” as the professional direction.`, financialGoal: `Update the money snapshot for “${name}”.`, relationship: `Make the next intentional step with “${name}”.`, creativeMedium: `Use “${name}” as the creative format.`, learningTopic: `Use “${name}” as the learning focus.`, healthRoutine: `Use “${name}” as the body routine.` },
    ru: { project: `Используйте «${name}» как контекст проекта.`, careerSkill: `Используйте «${name}» как профессиональное направление.`, financialGoal: `Обновите денежный снимок для «${name}».`, relationship: `Сделайте следующий осознанный шаг с «${name}».`, creativeMedium: `Используйте «${name}» как творческий формат.`, learningTopic: `Используйте «${name}» как фокус обучения.`, healthRoutine: `Используйте «${name}» как телесную рутину.` },
    cs: { project: `Použijte „${name}“ jako kontext projektu.`, careerSkill: `Použijte „${name}“ jako profesní směr.`, financialGoal: `Aktualizujte finanční přehled pro „${name}“.`, relationship: `Udělejte další vědomý krok s „${name}“.`, creativeMedium: `Použijte „${name}“ jako tvůrčí formát.`, learningTopic: `Použijte „${name}“ jako studijní zaměření.`, healthRoutine: `Použijte „${name}“ jako tělesnou rutinu.` },
    uk: { project: `Використайте «${name}» як контекст проєкту.`, careerSkill: `Використайте «${name}» як професійний напрям.`, financialGoal: `Оновіть фінансовий знімок для «${name}».`, relationship: `Зробіть наступний усвідомлений крок з «${name}».`, creativeMedium: `Використайте «${name}» як творчий формат.`, learningTopic: `Використайте «${name}» як фокус навчання.`, healthRoutine: `Використайте «${name}» як тілесну рутину.` }
  } satisfies Record<Locale, Record<UserFocusObject["type"], string>>;
  const prefix = prefixByType[locale][focusObject.type];
  const focusLabel = locale === "ru" ? "Текущий фокус" : locale === "cs" ? "Současné zaměření" : locale === "uk" ? "Поточний фокус" : "Current focus";
  return {
    ...definition,
    actionTitle: `${prefix} ${definition.actionTitle}`,
    concreteOutcome: `${definition.concreteOutcome} ${focusLabel}: ${focusObject.desiredOutcome}`
  };
}
