import type { Locale, MissionDefinition, UserFocusObject } from "./types";

type MissionTranslation = {
  actionTitle: string;
  concreteOutcome: string;
  recommendedChoice: string;
  exampleResult: string;
  inputs: Record<string, { label: string; placeholder?: string; example?: string }>;
  choices?: Record<string, string>;
  steps?: string[];
};

const ru: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Оцените энергию прямо сейчас", concreteOutcome: "Сохранена ясная оценка состояния тела.", recommendedChoice: "Оцените текущее состояние, не пытаясь сначала его улучшить.", exampleResult: "Энергия 3/5, стресс 2/5, мне мешает долгое сидение.", inputs: { energy: { label: "Энергия сейчас" }, stress: { label: "Стресс сейчас" }, "body-factor": { label: "Что сильнее всего влияет на тело сейчас?", placeholder: "Например: долго сижу" } } },
  "mind-root": { actionTitle: "Уберите лишнее и выберите следующий физический шаг", concreteOutcome: "Лишнее закрыто, а одно выполнимое действие сохранено.", recommendedChoice: "Закройте лишние вкладки и продолжите то, что ближе всего к завершению.", exampleResult: "Открыть файл страницы регистрации и закончить поле email.", inputs: { "workspace-cleared": { label: "Я закрыл лишние вкладки, приложения и материалы." }, "next-step": { label: "Какое физическое действие вы сделаете следующим?", placeholder: "Открыть… / Отправить… / Завершить…" } } },
  "finance-root": { actionTitle: "Введите четыре числа для финансового снимка", concreteOutcome: "Сохранены баланс, доход, постоянные и переменные расходы.", recommendedChoice: "Используйте приблизительные числа, если точные нельзя найти за две минуты.", exampleResult: "Баланс 1200; доход 2100; постоянные 1250; переменные 500.", inputs: { balance: { label: "Доступный баланс" }, income: { label: "Ожидаемый доход за месяц" }, "fixed-costs": { label: "Постоянные расходы за месяц" }, "flexible-spending": { label: "Ожидаемые переменные расходы" } } },
  "business-root": { actionTitle: "Выберите проект на эту главу", concreteOutcome: "Текущий проект и его видимый результат сохранены как объект фокуса.", recommendedChoice: "Выберите проект, который уже ближе всего к полезной видимой версии.", exampleResult: "Taskovo — рабочий экран регистрации, готовый для показа.", inputs: { "project-type": { label: "Над чем будем работать?" }, "project-name": { label: "Название проекта", placeholder: "Например: Taskovo" }, "desired-result": { label: "Какой видимый результат должен появиться?" } }, choices: { "site-app": "Сайт или приложение", "document-process": "Рабочий документ или процесс", "service-business": "Услуга или бизнес-идея", "creative-project": "Творческий проект" } },
  "career-root": { actionTitle: "Выберите ближайшую карьерную цель", concreteOutcome: "Практическая карьерная цель сохранена на эту главу.", recommendedChoice: "Выберите вариант, который даст видимое доказательство за 30 дней.", exampleResult: "Создать один кейс в портфолио для frontend-вакансий.", inputs: { "career-target": { label: "Какая карьерная цель сейчас ближе всего?" } }, choices: { "prove-skill": "Создать доказательство навыка", "improve-profile": "Улучшить резюме или профиль", "learn-skill": "Освоить полезный для роли навык", "explore-role": "Изучить реалистичную новую роль" } },
  "relationships-root": { actionTitle: "Выберите одного человека для осознанного контакта", concreteOutcome: "Одни отношения сохранены как текущий фокус.", recommendedChoice: "Выберите важного человека, с которым давно не общались.", exampleResult: "Анна — написать настоящее сообщение на этой неделе.", inputs: { "person-name": { label: "Имя человека", placeholder: "Например: Анна" }, "connection-outcome": { label: "Какой следующий шаг будет полезным?" } }, choices: { message: "Написать содержательное сообщение", call: "Договориться о коротком звонке", meet: "Предложить простую встречу", thanks: "Отправить конкретную благодарность" } },
  "creativity-root": { actionTitle: "Выберите формат и сделайте десятиминутный черновик", concreteOutcome: "Творческий формат сохранён, первый черновик создан.", recommendedChoice: "Используйте формат, который требует меньше всего подготовки.", exampleResult: "Текст — черновой первый абзац сохранён в заметках.", inputs: { "creative-medium": { label: "Какой формат вы используете?" } }, choices: { writing: "Текст", "drawing-design": "Рисунок или дизайн", "photo-video": "Фото или видео", "music-audio": "Музыка или аудио" } }
};

const cs: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Ohodnoťte svou energii právě teď", concreteOutcome: "Je uložen jasný snímek stavu těla.", recommendedChoice: "Ohodnoťte současný stav bez snahy jej nejdříve změnit.", exampleResult: "Energie 3/5, stres 2/5, vadí mi dlouhé sezení.", inputs: { energy: { label: "Energie právě teď" }, stress: { label: "Stres právě teď" }, "body-factor": { label: "Co teď nejvíce ovlivňuje vaše tělo?", placeholder: "Například: dlouhé sezení" } }, steps: ["Zastavte se a třikrát pomalu nadechněte.", "Ohodnoťte energii a stres od 1 do 5.", "Uložte hlavní vliv na svůj stav."] },
  "mind-root": { actionTitle: "Odstraňte rušivé věci a zvolte další fyzický krok", concreteOutcome: "Rušivé plochy jsou zavřené a jeden proveditelný krok je uložen.", recommendedChoice: "Zavřete nesouvisející karty a pokračujte v úkolu nejblíže dokončení.", exampleResult: "Otevřít soubor registrace a dokončit pole e-mailu.", inputs: { "workspace-cleared": { label: "Zavřel/a jsem nesouvisející karty, aplikace a materiály." }, "next-step": { label: "Jaký fyzický krok uděláte dál?", placeholder: "Otevřít… / Odeslat… / Dokončit…" } }, steps: ["Zavřete nesouvisející karty a aplikace.", "Pětkrát se pomalu nadechněte.", "Uložte jeden okamžitě proveditelný krok."] },
  "finance-root": { actionTitle: "Zadejte čtyři čísla finančního snímku", concreteOutcome: "Zůstatek, příjem, pevné a proměnlivé výdaje jsou uloženy.", recommendedChoice: "Použijte odhad, pokud přesné číslo nenajdete do dvou minut.", exampleResult: "Zůstatek 1200; příjem 2100; pevné 1250; proměnlivé 500.", inputs: { balance: { label: "Dostupný zůstatek" }, income: { label: "Očekávaný měsíční příjem" }, "fixed-costs": { label: "Pevné měsíční výdaje" }, "flexible-spending": { label: "Očekávané proměnlivé výdaje" } }, steps: ["Zkontrolujte dostupný zůstatek.", "Zadejte příjem a pevné náklady.", "Odhadněte proměnlivé výdaje."] },
  "business-root": { actionTitle: "Nastavte projekt pro tuto kapitolu", concreteOutcome: "Projekt a jeho viditelný výsledek jsou uloženy jako objekt zaměření.", recommendedChoice: "Vyberte projekt nejblíže užitečné viditelné verzi.", exampleResult: "Taskovo — funkční registrační obrazovka připravená k ukázce.", inputs: { "project-type": { label: "Na čem budete pracovat?" }, "project-name": { label: "Název projektu", placeholder: "Například: Taskovo" }, "desired-result": { label: "Jaký viditelný výsledek má vzniknout?" } }, choices: { "site-app": "Web nebo aplikace", "document-process": "Pracovní dokument nebo proces", "service-business": "Služba nebo podnikatelský nápad", "creative-project": "Tvůrčí projekt" } },
  "career-root": { actionTitle: "Zvolte nejbližší kariérní cíl", concreteOutcome: "Praktický kariérní cíl je uložen pro tuto kapitolu.", recommendedChoice: "Zvolte možnost, která vytvoří viditelný důkaz do 30 dnů.", exampleResult: "Vytvořit jeden portfolio případ pro frontendové role.", inputs: { "career-target": { label: "Jaký je váš nejbližší kariérní cíl?" } }, choices: { "prove-skill": "Vytvořit důkaz dovednosti", "improve-profile": "Zlepšit CV nebo profil", "learn-skill": "Naučit se dovednost pro roli", "explore-role": "Prozkoumat realistickou novou roli" } },
  "relationships-root": { actionTitle: "Vyberte jednoho člověka pro vědomý kontakt", concreteOutcome: "Jeden vztah je uložen jako současné zaměření.", recommendedChoice: "Vyberte důležitého člověka, kterému jste dlouho nenapsali.", exampleResult: "Anna — tento týden poslat opravdovou zprávu.", inputs: { "person-name": { label: "Jméno člověka", placeholder: "Například: Anna" }, "connection-outcome": { label: "Jaký další krok bude užitečný?" } }, choices: { message: "Poslat smysluplnou zprávu", call: "Domluvit krátký hovor", meet: "Navrhnout jednoduché setkání", thanks: "Poslat konkrétní poděkování" } },
  "creativity-root": { actionTitle: "Zvolte formát a vytvořte desetiminutový návrh", concreteOutcome: "Tvůrčí médium je uloženo a první návrh existuje.", recommendedChoice: "Použijte formát, který nyní vyžaduje nejméně přípravy.", exampleResult: "Psaní — hrubý úvodní odstavec uložený v poznámkách.", inputs: { "creative-medium": { label: "Jaký formát použijete?" } }, choices: { writing: "Psaní", "drawing-design": "Kresba nebo design", "photo-video": "Foto nebo video", "music-audio": "Hudba nebo zvuk" } }
};

const uk: Record<string, MissionTranslation> = {
  "health-root": { actionTitle: "Оцініть енергію просто зараз", concreteOutcome: "Збережено чіткий знімок стану тіла.", recommendedChoice: "Оцініть поточний стан, не намагаючись спочатку його змінити.", exampleResult: "Енергія 3/5, стрес 2/5, мені заважає довге сидіння.", inputs: { energy: { label: "Енергія зараз" }, stress: { label: "Стрес зараз" }, "body-factor": { label: "Що найбільше впливає на тіло зараз?", placeholder: "Наприклад: довго сиджу" } }, steps: ["Зупиніться і тричі повільно вдихніть.", "Оцініть енергію та стрес від 1 до 5.", "Збережіть головний вплив на ваш стан."] },
  "mind-root": { actionTitle: "Приберіть зайве й оберіть наступний фізичний крок", concreteOutcome: "Зайве закрито, одне здійсненне діяння збережено.", recommendedChoice: "Закрийте сторонні вкладки й продовжте те, що найближче до завершення.", exampleResult: "Відкрити файл сторінки реєстрації й завершити поле email.", inputs: { "workspace-cleared": { label: "Я закрив сторонні вкладки, застосунки й матеріали." }, "next-step": { label: "Яку фізичну дію ви зробите наступною?", placeholder: "Відкрити… / Надіслати… / Завершити…" } }, steps: ["Закрийте сторонні вкладки та застосунки.", "Зробіть п’ять повільних вдихів.", "Збережіть один крок, який можна почати негайно."] },
  "finance-root": { actionTitle: "Введіть чотири числа для фінансового знімка", concreteOutcome: "Збережено баланс, дохід, постійні й змінні витрати.", recommendedChoice: "Використайте приблизні числа, якщо точні не знайдете за дві хвилини.", exampleResult: "Баланс 1200; дохід 2100; постійні 1250; змінні 500.", inputs: { balance: { label: "Доступний баланс" }, income: { label: "Очікуваний місячний дохід" }, "fixed-costs": { label: "Постійні місячні витрати" }, "flexible-spending": { label: "Очікувані змінні витрати" } }, steps: ["Перевірте доступний баланс.", "Введіть дохід і постійні витрати.", "Оцініть змінні витрати."] },
  "business-root": { actionTitle: "Оберіть проєкт для цієї глави", concreteOutcome: "Проєкт і його видимий результат збережено як об’єкт фокусу.", recommendedChoice: "Оберіть проєкт, найближчий до корисної видимої версії.", exampleResult: "Taskovo — робочий екран реєстрації, готовий для показу.", inputs: { "project-type": { label: "Над чим будемо працювати?" }, "project-name": { label: "Назва проєкту", placeholder: "Наприклад: Taskovo" }, "desired-result": { label: "Який видимий результат має з’явитися?" } }, choices: { "site-app": "Сайт або застосунок", "document-process": "Робочий документ або процес", "service-business": "Послуга або бізнес-ідея", "creative-project": "Творчий проєкт" } },
  "career-root": { actionTitle: "Оберіть найближчу кар’єрну ціль", concreteOutcome: "Практичну кар’єрну ціль збережено для цієї глави.", recommendedChoice: "Оберіть варіант, що дасть видимий доказ за 30 днів.", exampleResult: "Створити один кейс у портфоліо для frontend-ролей.", inputs: { "career-target": { label: "Яка кар’єрна ціль зараз найближча?" } }, choices: { "prove-skill": "Створити доказ навички", "improve-profile": "Покращити резюме або профіль", "learn-skill": "Вивчити корисну для ролі навичку", "explore-role": "Дослідити реалістичну нову роль" } },
  "relationships-root": { actionTitle: "Оберіть одну людину для свідомого контакту", concreteOutcome: "Одні стосунки збережено як поточний фокус.", recommendedChoice: "Оберіть важливу людину, з якою давно не спілкувалися.", exampleResult: "Анна — написати змістовне повідомлення цього тижня.", inputs: { "person-name": { label: "Ім’я людини", placeholder: "Наприклад: Анна" }, "connection-outcome": { label: "Який наступний крок буде корисним?" } }, choices: { message: "Написати змістовне повідомлення", call: "Домовитися про короткий дзвінок", meet: "Запропонувати просту зустріч", thanks: "Надіслати конкретну подяку" } },
  "creativity-root": { actionTitle: "Оберіть формат і зробіть десятихвилинну чернетку", concreteOutcome: "Творчий формат збережено, перша чернетка створена.", recommendedChoice: "Використайте формат, що потребує найменше підготовки.", exampleResult: "Текст — чернетку першого абзацу збережено в нотатках.", inputs: { "creative-medium": { label: "Який формат ви використаєте?" } }, choices: { writing: "Текст", "drawing-design": "Малюнок або дизайн", "photo-video": "Фото або відео", "music-audio": "Музика або аудіо" } }
};

export function localizeMissionDefinition(definition: MissionDefinition, locale: Locale): MissionDefinition {
  if (locale === "en") return definition;
  const translation = (locale === "ru" ? ru : locale === "cs" ? cs : uk)[definition.technologyId];
  if (!translation) {
    const generic = locale === "ru"
      ? { label: "Что стало доступно после этой сессии?", placeholder: "Опишите один видимый результат", recommended: "Завершите минимальную видимую версию, описанную в шагах миссии." }
      : locale === "cs"
        ? { label: "Co je po této relaci dostupné?", placeholder: "Popište jeden viditelný výsledek", recommended: "Dokončete nejmenší viditelnou verzi popsanou v krocích mise." }
        : { label: "Що стало доступним після цієї сесії?", placeholder: "Опишіть один видимий результат", recommended: "Завершіть найменшу видиму версію, описану в кроках місії." };
    return { ...definition, recommendedChoice: generic.recommended, inputSchema: definition.inputSchema.map((input) => input.id === "result" ? { ...input, label: generic.label, placeholder: generic.placeholder } : input) };
  }
  return {
    ...definition,
    actionTitle: translation.actionTitle,
    concreteOutcome: translation.concreteOutcome,
    recommendedChoice: translation.recommendedChoice,
    exampleResult: translation.exampleResult,
    exactSteps: translation.steps ? translation.steps.map((instruction, index) => ({ id: `step-${index + 1}`, instruction })) : definition.exactSteps,
    inputSchema: definition.inputSchema.map((input) => ({
      ...input,
      ...translation.inputs[input.id],
      choices: input.choices?.map((choice) => ({ ...choice, label: translation.choices?.[choice.id] ?? choice.label }))
    }))
  };
}

export function applyFocusObject(definition: MissionDefinition, focusObject: UserFocusObject | undefined, locale: Locale): MissionDefinition {
  if (!focusObject || definition.technologyId.endsWith("-root")) return definition;
  const prefix = locale === "ru" ? `Откройте «${focusObject.name}» и выполните действие.` : locale === "cs" ? `Otevřete „${focusObject.name}“ a proveďte akci.` : locale === "uk" ? `Відкрийте «${focusObject.name}» і виконайте дію.` : `Open “${focusObject.name}” and complete the action.`;
  const focusLabel = locale === "ru" ? "Текущий фокус" : locale === "cs" ? "Současné zaměření" : locale === "uk" ? "Поточний фокус" : "Current focus";
  return {
    ...definition,
    actionTitle: `${prefix} ${definition.actionTitle}`,
    concreteOutcome: `${definition.concreteOutcome} ${focusLabel}: ${focusObject.desiredOutcome}`
  };
}
